export const FETCH_REGISTER_PENDING = "FETCH_REGISTER_PENDING";
export const FETCH_REGISTER_SUCCESS = "FETCH_REGISTER_SUCCESS";
export const FETCH_REGISTER_FAILURE = "FETCH_REGISTER_FAILURE";
export const FETCH_REGISTER_ERROR = "FETCH_REGISTER_ERROR";
