export const SET_LOGIN_PENDING = "SET_LOGIN_PENDING";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGIN_FAILURE = "SET_LOGIN_FAILURE";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGOUT = "SET_LOGOUT";
